/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author hemantsharma
 */
public class CalculatorUI extends javax.swing.JFrame {
    
    private static boolean resultShown;
    private static float numberOne;
    private static float numberTwo;
    private static String operand;

    /**
     * Creates new form CalculatorUI
     */
    public CalculatorUI() {
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculatorPanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        signButton = new javax.swing.JButton();
        percentageOperand = new javax.swing.JButton();
        divisionOperand = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        multiplyOperand = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        minusOperand = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        plusOperand = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        decimalPoint = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        displayField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Swing Calculator");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        clearButton.setText("C");
        clearButton.setSize(new java.awt.Dimension(60, 50));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        signButton.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        signButton.setText("+/-");
        signButton.setSize(new java.awt.Dimension(60, 50));
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });

        percentageOperand.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        percentageOperand.setText("%");
        percentageOperand.setSize(new java.awt.Dimension(60, 50));
        percentageOperand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageOperandActionPerformed(evt);
            }
        });

        divisionOperand.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        divisionOperand.setText("/");
        divisionOperand.setSize(new java.awt.Dimension(60, 50));
        divisionOperand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionOperandActionPerformed(evt);
            }
        });

        number7.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number7.setText("7");
        number7.setSize(new java.awt.Dimension(60, 50));
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number8.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number8.setText("8");
        number8.setSize(new java.awt.Dimension(60, 50));
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number9.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number9.setText("9");
        number9.setSize(new java.awt.Dimension(60, 50));
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        multiplyOperand.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        multiplyOperand.setText("*");
        multiplyOperand.setSize(new java.awt.Dimension(60, 50));
        multiplyOperand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyOperandActionPerformed(evt);
            }
        });

        number4.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number4.setText("4");
        number4.setSize(new java.awt.Dimension(60, 50));
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number5.setText("5");
        number5.setSize(new java.awt.Dimension(60, 50));
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number6.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number6.setText("6");
        number6.setSize(new java.awt.Dimension(60, 50));
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        minusOperand.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        minusOperand.setText("-");
        minusOperand.setSize(new java.awt.Dimension(60, 50));
        minusOperand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusOperandActionPerformed(evt);
            }
        });

        number1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number1.setText("1");
        number1.setSize(new java.awt.Dimension(60, 50));
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number2.setText("2");
        number2.setSize(new java.awt.Dimension(60, 50));
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberInput(evt);
            }
        });

        number3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number3.setText("3");
        number3.setSize(new java.awt.Dimension(60, 50));
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        plusOperand.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        plusOperand.setText("+");
        plusOperand.setSize(new java.awt.Dimension(60, 50));
        plusOperand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusOperandActionPerformed(evt);
            }
        });

        number0.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        number0.setText("0");
        number0.setSize(new java.awt.Dimension(60, 50));
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        decimalPoint.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        decimalPoint.setText(".");
        decimalPoint.setSize(new java.awt.Dimension(60, 50));
        decimalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalPointActionPerformed(evt);
            }
        });

        equalsButton.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        equalsButton.setText("=");
        equalsButton.setSize(new java.awt.Dimension(60, 50));
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        displayField.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        displayField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        displayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculatorPanelLayout = new javax.swing.GroupLayout(CalculatorPanel);
        CalculatorPanel.setLayout(CalculatorPanelLayout);
        CalculatorPanelLayout.setHorizontalGroup(
            CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayField)
                    .addGroup(CalculatorPanelLayout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentageOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divisionOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPanelLayout.createSequentialGroup()
                        .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiplyOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPanelLayout.createSequentialGroup()
                        .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPanelLayout.createSequentialGroup()
                        .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CalculatorPanelLayout.createSequentialGroup()
                                .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decimalPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CalculatorPanelLayout.createSequentialGroup()
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plusOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
        );
        CalculatorPanelLayout.setVerticalGroup(
            CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentageOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusOperand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimalPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents() {
        CalculatorUI.resultShown = false;
        CalculatorUI.numberOne = 0.0f;
        CalculatorUI.numberTwo = 0.0f;
        CalculatorUI.operand = "";
        setResizable(false);
    }
    
    private void decimalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalPointActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + ".";
        displayField.setText(text);
    }//GEN-LAST:event_decimalPointActionPerformed

    private void numberInput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberInput
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "2";
        displayField.setText(text);
    }//GEN-LAST:event_numberInput

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "0";
        displayField.setText(text);        
    }//GEN-LAST:event_number0ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "1";
        displayField.setText(text);
    }//GEN-LAST:event_number1ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "3";
        displayField.setText(text);
    }//GEN-LAST:event_number3ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "4";
        displayField.setText(text);
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "5";
        displayField.setText(text);
    }//GEN-LAST:event_number5ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "6";
        displayField.setText(text);
    }//GEN-LAST:event_number6ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "7";
        displayField.setText(text);
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "8";
        displayField.setText(text);
    }//GEN-LAST:event_number8ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        if(CalculatorUI.resultShown) {
            displayField.setText("");
            CalculatorUI.resultShown = false;
        }
        String text = displayField.getText() + "9";
        displayField.setText(text);
    }//GEN-LAST:event_number9ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        displayField.setText("");
        resultShown = false;
    }//GEN-LAST:event_clearButtonActionPerformed

    private void displayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayFieldActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        if(displayField.getText().charAt(0) == '-')
            displayField.setText(displayField.getText().substring(1));
        else
            displayField.setText("-" + displayField.getText());
    }//GEN-LAST:event_signButtonActionPerformed

    private void percentageOperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageOperandActionPerformed
        try {
            float input = Float.parseFloat(displayField.getText());
            input /= 100;
            displayField.setText(String.valueOf(input));
            resultShown = true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
        }
    }//GEN-LAST:event_percentageOperandActionPerformed

    private void divisionOperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionOperandActionPerformed
        try {
            CalculatorUI.numberOne = Float.parseFloat(displayField.getText());
            CalculatorUI.operand = "/";
            displayField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
        }
    }//GEN-LAST:event_divisionOperandActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        try {
            CalculatorUI.numberTwo = Float.parseFloat(displayField.getText());
            switch(CalculatorUI.operand) {
                case "+":
                    CalculatorUI.numberOne += CalculatorUI.numberTwo;
                    break;
                case "-":
                    CalculatorUI.numberOne -= CalculatorUI.numberTwo;
                    break;
                case "/":
                    CalculatorUI.numberOne /= CalculatorUI.numberTwo;
                    break;
                case "*":
                    CalculatorUI.numberOne *= CalculatorUI.numberTwo;
                    break;
                default: 
                    JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
            }
            displayField.setText(String.valueOf(CalculatorUI.numberOne));
            CalculatorUI.resultShown = true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
        }
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void multiplyOperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyOperandActionPerformed
        try {
            CalculatorUI.numberOne = Float.parseFloat(displayField.getText());
            CalculatorUI.operand = "*";
            displayField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
        }
    }//GEN-LAST:event_multiplyOperandActionPerformed

    private void minusOperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusOperandActionPerformed
        try {
            CalculatorUI.numberOne = Float.parseFloat(displayField.getText());
            CalculatorUI.operand = "-";
            displayField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
        }
    }//GEN-LAST:event_minusOperandActionPerformed

    private void plusOperandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusOperandActionPerformed
        try {
            CalculatorUI.numberOne = Float.parseFloat(displayField.getText());
            CalculatorUI.operand = "+";
            displayField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Operation");
        }
    }//GEN-LAST:event_plusOperandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalculatorPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimalPoint;
    private javax.swing.JTextField displayField;
    private javax.swing.JButton divisionOperand;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton minusOperand;
    private javax.swing.JButton multiplyOperand;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton percentageOperand;
    private javax.swing.JButton plusOperand;
    private javax.swing.JButton signButton;
    // End of variables declaration//GEN-END:variables

    private void setDisplayField(String string) {
        displayField.setText(string);
    }
}
